/* The following code was generated by JFlex 1.6.1 */

package jadelex ;

import jade.Direction;

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.1
 * from the specification file <tt>src/jadelex/jade.lex</tt>
 */
public class TokenizerV1 implements Tokenizer {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\17\1\23\1\23\1\23\1\23\22\0\1\17\11\0\1\24"+
    "\4\0\1\22\12\20\7\0\32\25\6\0\1\6\1\5\1\25\1\13"+
    "\1\2\1\21\2\25\1\7\2\25\1\1\1\25\1\11\1\12\1\16"+
    "\1\25\1\4\1\10\1\15\1\14\1\3\4\25\12\0\1\23\32\0"+
    "\1\17\11\0\1\25\12\0\1\25\4\0\1\25\5\0\27\25\1\0"+
    "\37\25\1\0\u01ca\25\4\0\14\25\16\0\5\25\7\0\1\25\1\0"+
    "\1\25\201\0\5\25\1\0\2\25\2\0\4\25\1\0\1\25\6\0"+
    "\1\25\1\0\3\25\1\0\1\25\1\0\24\25\1\0\123\25\1\0"+
    "\213\25\10\0\246\25\1\0\46\25\2\0\1\25\7\0\47\25\110\0"+
    "\33\25\5\0\3\25\55\0\53\25\43\0\2\25\1\0\143\25\1\0"+
    "\1\25\17\0\2\25\7\0\2\25\12\0\3\25\2\0\1\25\20\0"+
    "\1\25\1\0\36\25\35\0\131\25\13\0\1\25\30\0\41\25\11\0"+
    "\2\25\4\0\1\25\5\0\26\25\4\0\1\25\11\0\1\25\3\0"+
    "\1\25\27\0\31\25\107\0\23\25\121\0\66\25\3\0\1\25\22\0"+
    "\1\25\7\0\12\25\17\0\20\25\4\0\10\25\2\0\2\25\2\0"+
    "\26\25\1\0\7\25\1\0\1\25\3\0\4\25\3\0\1\25\20\0"+
    "\1\25\15\0\2\25\1\0\3\25\16\0\2\25\23\0\6\25\4\0"+
    "\2\25\2\0\26\25\1\0\7\25\1\0\2\25\1\0\2\25\1\0"+
    "\2\25\37\0\4\25\1\0\1\25\23\0\3\25\20\0\11\25\1\0"+
    "\3\25\1\0\26\25\1\0\7\25\1\0\2\25\1\0\5\25\3\0"+
    "\1\25\22\0\1\25\17\0\2\25\43\0\10\25\2\0\2\25\2\0"+
    "\26\25\1\0\7\25\1\0\2\25\1\0\5\25\3\0\1\25\36\0"+
    "\2\25\1\0\3\25\17\0\1\25\21\0\1\25\1\0\6\25\3\0"+
    "\3\25\1\0\4\25\3\0\2\25\1\0\1\25\1\0\2\25\3\0"+
    "\2\25\3\0\3\25\3\0\14\25\26\0\1\25\64\0\10\25\1\0"+
    "\3\25\1\0\27\25\1\0\20\25\3\0\1\25\32\0\2\25\6\0"+
    "\2\25\43\0\10\25\1\0\3\25\1\0\27\25\1\0\12\25\1\0"+
    "\5\25\3\0\1\25\40\0\1\25\1\0\2\25\17\0\2\25\22\0"+
    "\10\25\1\0\3\25\1\0\51\25\2\0\1\25\20\0\1\25\21\0"+
    "\2\25\30\0\6\25\5\0\22\25\3\0\30\25\1\0\11\25\1\0"+
    "\1\25\2\0\7\25\72\0\60\25\1\0\2\25\14\0\7\25\72\0"+
    "\2\25\1\0\1\25\2\0\2\25\1\0\1\25\2\0\1\25\6\0"+
    "\4\25\1\0\7\25\1\0\3\25\1\0\1\25\1\0\1\25\2\0"+
    "\2\25\1\0\4\25\1\0\2\25\11\0\1\25\2\0\5\25\1\0"+
    "\1\25\25\0\4\25\40\0\1\25\77\0\10\25\1\0\44\25\33\0"+
    "\5\25\163\0\53\25\24\0\1\25\20\0\6\25\4\0\4\25\3\0"+
    "\1\25\3\0\2\25\7\0\3\25\4\0\15\25\14\0\1\25\21\0"+
    "\46\25\1\0\1\25\5\0\1\25\2\0\53\25\1\0\u014d\25\1\0"+
    "\4\25\2\0\7\25\1\0\1\25\1\0\4\25\2\0\51\25\1\0"+
    "\4\25\2\0\41\25\1\0\4\25\2\0\7\25\1\0\1\25\1\0"+
    "\4\25\2\0\17\25\1\0\71\25\1\0\4\25\2\0\103\25\45\0"+
    "\20\25\20\0\125\25\14\0\u026c\25\2\0\21\25\1\17\32\25\5\0"+
    "\113\25\6\0\10\25\7\0\15\25\1\0\4\25\16\0\22\25\16\0"+
    "\22\25\16\0\15\25\1\0\3\25\17\0\64\25\43\0\1\25\4\0"+
    "\1\25\103\0\130\25\10\0\51\25\1\0\1\25\5\0\106\25\12\0"+
    "\37\25\61\0\36\25\2\0\5\25\13\0\54\25\25\0\7\25\70\0"+
    "\27\25\11\0\65\25\122\0\1\25\135\0\57\25\21\0\7\25\67\0"+
    "\36\25\15\0\2\25\12\0\54\25\32\0\44\25\51\0\3\25\12\0"+
    "\44\25\153\0\4\25\1\0\4\25\3\0\2\25\11\0\300\25\100\0"+
    "\u0116\25\2\0\6\25\2\0\46\25\2\0\6\25\2\0\10\25\1\0"+
    "\1\25\1\0\1\25\1\0\1\25\1\0\37\25\2\0\65\25\1\0"+
    "\7\25\1\0\1\25\3\0\3\25\1\0\7\25\3\0\4\25\2\0"+
    "\6\25\4\0\15\25\5\0\3\25\1\0\7\25\3\0\13\17\35\0"+
    "\1\23\1\23\5\0\1\17\57\0\1\17\21\0\1\25\15\0\1\25"+
    "\20\0\15\25\145\0\1\25\4\0\1\25\2\0\12\25\1\0\1\25"+
    "\3\0\5\25\6\0\1\25\1\0\1\25\1\0\1\25\1\0\4\25"+
    "\1\0\13\25\2\0\4\25\5\0\5\25\4\0\1\25\64\0\2\25"+
    "\u0a7b\0\57\25\1\0\57\25\1\0\205\25\6\0\4\25\3\0\2\25"+
    "\14\0\46\25\1\0\1\25\5\0\1\25\2\0\70\25\7\0\1\25"+
    "\20\0\27\25\11\0\7\25\1\0\7\25\1\0\7\25\1\0\7\25"+
    "\1\0\7\25\1\0\7\25\1\0\7\25\1\0\7\25\120\0\1\25"+
    "\u01d0\0\1\17\4\0\2\25\52\0\5\25\5\0\2\25\4\0\126\25"+
    "\6\0\3\25\1\0\132\25\1\0\4\25\5\0\51\25\3\0\136\25"+
    "\21\0\33\25\65\0\20\25\u0200\0\u19b6\25\112\0\u51cd\25\63\0\u048d\25"+
    "\103\0\56\25\2\0\u010d\25\3\0\20\25\12\0\2\25\24\0\57\25"+
    "\20\0\37\25\2\0\106\25\61\0\11\25\2\0\147\25\2\0\4\25"+
    "\1\0\36\25\2\0\2\25\105\0\13\25\1\0\3\25\1\0\4\25"+
    "\1\0\27\25\35\0\64\25\16\0\62\25\76\0\6\25\3\0\1\25"+
    "\16\0\34\25\12\0\27\25\31\0\35\25\7\0\57\25\34\0\1\25"+
    "\20\0\5\25\1\0\12\25\12\0\5\25\1\0\51\25\27\0\3\25"+
    "\1\0\10\25\24\0\27\25\3\0\1\25\3\0\62\25\1\0\1\25"+
    "\3\0\2\25\2\0\5\25\2\0\1\25\1\0\1\25\30\0\3\25"+
    "\2\0\13\25\7\0\3\25\14\0\6\25\2\0\6\25\2\0\6\25"+
    "\11\0\7\25\1\0\7\25\1\0\53\25\1\0\4\25\4\0\2\25"+
    "\132\0\43\25\35\0\u2ba4\25\14\0\27\25\4\0\61\25\u2104\0\u016e\25"+
    "\2\0\152\25\46\0\7\25\14\0\5\25\5\0\1\25\1\0\12\25"+
    "\1\0\15\25\1\0\5\25\1\0\1\25\1\0\2\25\1\0\2\25"+
    "\1\0\154\25\41\0\u016b\25\22\0\100\25\2\0\66\25\50\0\14\25"+
    "\164\0\5\25\1\0\207\25\44\0\32\25\6\0\32\25\13\0\131\25"+
    "\3\0\6\25\2\0\6\25\2\0\6\25\2\0\3\25\43\0\14\25"+
    "\1\0\32\25\1\0\23\25\1\0\2\25\1\0\17\25\2\0\16\25"+
    "\42\0\173\25\u0185\0\35\25\3\0\61\25\57\0\40\25\20\0\21\25"+
    "\1\0\10\25\6\0\46\25\12\0\36\25\2\0\44\25\4\0\10\25"+
    "\60\0\236\25\142\0\50\25\10\0\64\25\234\0\u0137\25\11\0\26\25"+
    "\12\0\10\25\230\0\6\25\2\0\1\25\1\0\54\25\1\0\2\25"+
    "\3\0\1\25\2\0\27\25\12\0\27\25\11\0\37\25\141\0\26\25"+
    "\12\0\32\25\106\0\70\25\6\0\2\25\100\0\1\25\17\0\4\25"+
    "\1\0\3\25\1\0\33\25\54\0\35\25\3\0\35\25\43\0\10\25"+
    "\1\0\34\25\33\0\66\25\12\0\26\25\12\0\23\25\15\0\22\25"+
    "\156\0\111\25\u03ba\0\65\25\113\0\55\25\40\0\31\25\32\0\44\25"+
    "\51\0\43\25\3\0\1\25\14\0\60\25\16\0\4\25\25\0\1\25"+
    "\45\0\22\25\1\0\31\25\204\0\57\25\46\0\10\25\2\0\2\25"+
    "\2\0\26\25\1\0\7\25\1\0\2\25\1\0\5\25\3\0\1\25"+
    "\37\0\5\25\u011e\0\60\25\24\0\2\25\1\0\1\25\270\0\57\25"+
    "\121\0\60\25\24\0\1\25\73\0\53\25\u01f5\0\100\25\37\0\1\25"+
    "\u01c0\0\71\25\u0507\0\u0399\25\u0c67\0\u042f\25\u33d1\0\u0239\25\7\0\37\25"+
    "\161\0\36\25\22\0\60\25\20\0\4\25\37\0\25\25\5\0\23\25"+
    "\u0370\0\105\25\13\0\1\25\102\0\15\25\u4060\0\2\25\u0bfe\0\153\25"+
    "\5\0\15\25\3\0\11\25\7\0\12\25\u1766\0\125\25\1\0\107\25"+
    "\1\0\2\25\2\0\1\25\2\0\2\25\2\0\4\25\1\0\14\25"+
    "\1\0\1\25\1\0\7\25\1\0\101\25\1\0\4\25\2\0\10\25"+
    "\1\0\7\25\1\0\34\25\1\0\4\25\1\0\5\25\1\0\1\25"+
    "\3\0\7\25\1\0\u0154\25\2\0\31\25\1\0\31\25\1\0\37\25"+
    "\1\0\31\25\1\0\37\25\1\0\31\25\1\0\37\25\1\0\31\25"+
    "\1\0\37\25\1\0\31\25\1\0\10\25\u1034\0\305\25\u053b\0\4\25"+
    "\1\0\33\25\1\0\2\25\1\0\1\25\2\0\1\25\1\0\12\25"+
    "\1\0\4\25\1\0\1\25\1\0\1\25\6\0\1\25\4\0\1\25"+
    "\1\0\1\25\1\0\1\25\1\0\3\25\1\0\2\25\1\0\1\25"+
    "\2\0\1\25\1\0\1\25\1\0\1\25\1\0\1\25\1\0\1\25"+
    "\1\0\2\25\1\0\1\25\2\0\4\25\1\0\7\25\1\0\4\25"+
    "\1\0\4\25\1\0\1\25\1\0\12\25\1\0\21\25\5\0\3\25"+
    "\1\0\5\25\1\0\21\25\u1144\0\ua6d7\25\51\0\u1035\25\13\0\336\25"+
    "\u3fe2\0\u021e\25\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\u05f0\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\12\2\1\1\10\2\1\0\1\1\1\0"+
    "\1\2\1\3\2\2\1\4\3\2\2\0\3\2\1\5"+
    "\1\2\2\0\1\6\2\2\1\7\1\10\1\0\1\2"+
    "\1\0\1\11\1\12\2\0\1\13";

  private static int [] zzUnpackAction() {
    int [] result = new int[54];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\26\0\54\0\102\0\130\0\156\0\204\0\232"+
    "\0\260\0\306\0\334\0\362\0\u0108\0\u011e\0\u0134\0\u014a"+
    "\0\u0160\0\u0176\0\u018c\0\u01a2\0\u01b8\0\u01ce\0\u01e4\0\u01fa"+
    "\0\u0210\0\130\0\u0226\0\u023c\0\130\0\u0252\0\u0268\0\u027e"+
    "\0\u0294\0\u02aa\0\u02c0\0\u02d6\0\u02ec\0\130\0\u0302\0\u0318"+
    "\0\u032e\0\130\0\u0344\0\u035a\0\130\0\u0318\0\u0370\0\u0386"+
    "\0\u039c\0\26\0\130\0\u03b2\0\u03c8\0\u03c8";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[54];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\2\5\1\6\1\7\1\5\1\10"+
    "\1\11\1\12\3\5\1\13\1\2\1\14\1\5\1\15"+
    "\2\2\1\5\27\0\1\5\1\16\14\5\1\0\2\5"+
    "\3\0\1\5\1\0\7\5\1\17\6\5\1\0\2\5"+
    "\3\0\1\5\1\0\16\5\1\0\2\5\3\0\1\5"+
    "\1\0\5\5\1\20\10\5\1\0\2\5\3\0\1\5"+
    "\1\0\1\21\15\5\1\0\2\5\3\0\1\5\1\0"+
    "\13\5\1\22\2\5\1\0\2\5\3\0\1\5\1\0"+
    "\11\5\1\23\4\5\1\0\2\5\3\0\1\5\1\0"+
    "\13\5\1\24\2\5\1\0\2\5\3\0\1\5\1\0"+
    "\5\5\1\25\10\5\1\0\2\5\3\0\1\5\1\0"+
    "\16\5\1\26\1\14\1\5\1\0\1\26\1\0\1\5"+
    "\22\0\1\27\1\0\1\30\2\0\2\5\1\31\13\5"+
    "\1\0\2\5\3\0\1\5\1\0\14\5\1\32\1\5"+
    "\1\0\2\5\3\0\1\5\1\0\6\5\1\33\7\5"+
    "\1\0\2\5\3\0\1\5\1\0\1\34\15\5\1\0"+
    "\2\5\3\0\1\5\1\0\12\5\1\35\3\5\1\0"+
    "\2\5\3\0\1\5\1\0\3\5\1\36\12\5\1\0"+
    "\2\5\3\0\1\5\1\0\1\5\1\37\14\5\1\0"+
    "\2\5\3\0\1\5\1\0\7\5\1\40\6\5\1\0"+
    "\2\5\3\0\1\5\21\0\1\41\4\0\23\27\1\0"+
    "\2\27\22\30\1\0\1\30\1\42\1\30\1\0\1\5"+
    "\1\43\14\5\1\0\2\5\3\0\1\5\1\0\7\5"+
    "\1\44\6\5\1\0\2\5\3\0\1\5\1\0\1\5"+
    "\1\45\14\5\1\0\2\5\3\0\1\5\1\0\12\5"+
    "\1\46\3\5\1\0\2\5\3\0\1\5\1\0\7\5"+
    "\1\47\6\5\1\0\2\5\3\0\1\5\1\0\16\5"+
    "\1\50\2\5\1\0\1\50\1\0\1\5\12\0\1\51"+
    "\35\0\1\2\4\0\3\5\1\52\12\5\1\0\2\5"+
    "\3\0\1\5\1\0\7\5\1\53\6\5\1\0\2\5"+
    "\3\0\1\5\1\0\3\5\1\54\12\5\1\0\2\5"+
    "\3\0\1\5\1\0\14\5\1\55\1\5\1\0\2\5"+
    "\3\0\1\5\20\0\1\56\14\0\1\57\17\0\1\5"+
    "\1\60\14\5\1\0\2\5\3\0\1\5\1\0\16\5"+
    "\1\61\2\5\1\0\1\61\1\0\1\5\10\0\1\62"+
    "\16\0\3\5\1\63\12\5\1\0\2\5\3\0\1\5"+
    "\20\0\1\64\24\0\1\65\1\64\2\0\1\65\22\0"+
    "\1\66\5\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[990];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\23\1\1\0\1\1\1\0\10\1\2\0"+
    "\5\1\2\0\5\1\1\0\1\1\1\0\1\11\1\1"+
    "\2\0\1\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[54];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public TokenizerV1(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 2274) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public Yytoken yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
        return null;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { 
            }
          case 12: break;
          case 2: 
            { return new Unknown(yytext());
            }
          case 13: break;
          case 3: 
            { return new Move(Direction.EAST);
            }
          case 14: break;
          case 4: 
            { return new Move(Direction.SOUTH);
            }
          case 15: break;
          case 5: 
            { return new Move(Direction.NORTH);
            }
          case 16: break;
          case 6: 
            { return new PenMode(false);
            }
          case 17: break;
          case 7: 
            { return new Move(Direction.WEST);
            }
          case 18: break;
          case 8: 
            { return new StepLength(Integer.parseInt(yytext().split(" ")[1]));
            }
          case 19: break;
          case 9: 
            { return new Repeat(Integer.parseInt(yytext().split(" ")[0]));
            }
          case 20: break;
          case 10: 
            { return new PenMode(true);
            }
          case 21: break;
          case 11: 
            { String[] parts = yytext().split(" ");
	return new Jump(Integer.parseInt(parts[1]), Integer.parseInt(parts[2]));
            }
          case 22: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
